# Generated by Django 3.0.8 on 2020-08-06 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_giving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_giving_follow', to=settings.AUTH_USER_MODEL)),
                ('id_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=155)),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_giving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_giving_notification', to=settings.AUTH_USER_MODEL)),
                ('id_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
